apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata: {}
spec:
  desiredState:
    interfaces:
    - ipv4:
        address:
        - ip: 10.0.10.2
          prefix-length: 24
        enabled: true
        gateway: 10.0.10.1
      name: bond0.10
      state: up
      type: vlan
      vlan:
        base-iface: bond0
        id: 10
    - ipv4:
        address:
        - ip: 10.0.20.2
          prefix-length: 24
        enabled: true
        gateway: 10.0.20.1
      name: bond0.20
      state: up
      type: vlan
      vlan:
        base-iface: bond0
        id: 20
    - bond:
        mode: 802.3ad
        options: {}
      name: bond0
      state: up
      type: bond
    - ipv4:
        address:
        - ip: 10.0.30.2
          prefix-length: 24
        enabled: true
        gateway: 10.0.30.1
      name: bond1.30
      state: up
      type: vlan
      vlan:
        base-iface: bond1
        id: 30
    - ipv4:
        address:
        - ip: 10.0.40.2
          prefix-length: 24
        enabled: true
        gateway: 10.0.40.1
      name: bond1.40
      state: up
      type: vlan
      vlan:
        base-iface: bond1
        id: 40
    - bond:
        mode: 802.3ad
        options: {}
      name: bond1
      state: up
      type: bond
  nodeSelector: {}
