apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: Linux Bridge and VLAN Configs
spec:
  desiredState:
    dns-resolver:
      config:
        search:
        - example.com
        server:
        - 192.168.1.1
    interfaces:
    - bridge:
        port:
        - name: nic1
        - name: nic2
      ipv4:
        dhcp: false
        enabled: true
      name: br1
      state: up
      type: linux-bridge
    - ipv4:
        address:
        - ip: 192.168.100.1
          prefix-length: 24
        enabled: true
        gateway: 192.168.100.254
      name: br1.vlan100
      state: up
      type: vlan
      vlan:
        base-iface: br1
        id: 100
    - ipv4:
        address:
        - ip: 192.168.200.1
          prefix-length: 24
        enabled: true
        gateway: 192.168.200.254
      name: br1.vlan200
      state: up
      type: vlan
      vlan:
        base-iface: br1
        id: 200
    - ipv4:
        address:
        - ip: 10.0.10.2
          prefix-length: 24
        enabled: true
        gateway: 10.0.10.1
      name: bond0.10
      state: up
      type: vlan
      vlan:
        base-iface: bond0
        id: 10
    - ipv4:
        address:
        - ip: 10.0.20.2
          prefix-length: 24
        enabled: true
        gateway: 10.0.20.1
      name: bond0.20
      state: up
      type: vlan
      vlan:
        base-iface: bond0
        id: 20
    - ipv4:
        address:
        - ip: 10.0.30.2
          prefix-length: 24
        enabled: true
        gateway: 10.0.30.1
      name: bond1.30
      state: up
      type: vlan
      vlan:
        base-iface: bond1
        id: 30
    - ipv4:
        address:
        - ip: 10.0.40.2
          prefix-length: 24
        enabled: true
        gateway: 10.0.40.1
      name: bond1.40
      state: up
      type: vlan
      vlan:
        base-iface: bond1
        id: 40
  nodeSelector:
    kubernetes.io/hostname: node01
